version: '3.8'
services:
  backend:
    build:
      context: ./back-end
    container_name: backend
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./nginx
      args:
        VITE_API_URL: http://backend:3000/api
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped 