version: "3.8"

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"      
    restart: unless-stopped

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"       
    restart: unless-stopped
